export const SITE_COPY = {
  en: {
    bio1_title: "The Beginning",
    bio1_range: "1928 — 1951",
    bio1_text:
      "Born Stephen Wechsler in New York City, Victor's journey began in the vibrant political atmosphere of a Jewish-American family. By the time he reached Harvard University, his worldview had sharpened into a commitment to social justice that would define every subsequent year of his long life.",
    bio2_title: "The Danube Leap",
    bio2_text:
      "Facing the prospect of a military tribunal for his past affiliations, Stephen made his move. On August 12, 1952, he swam across the Danube near Linz, seeking asylum in the Soviet Zone. It was a swim away from one life, and toward another that would last over seven decades.",
    bio3_title: "Witness to Two Worlds",
    bio3_text:
      "Reborn as Victor Grossman in the GDR, he became a unique historical anomaly—the only person to graduate from both Harvard University and Karl Marx University in Leipzig. For decades, he served as an author, activist, journalist, translator, and bridge between East and West.",
    memorial_title: "Eulogy & Memorial",
    photo_archive: "Photographic Archive",
    photo_sub: "A curated history through images and shared memories",
    photo_upload: "Upload Photo",
    memories_title: "Wall of Memories",
    memories_btn: "Post Tribute",
    books_title: "Books & Publications",
    books_amazon: "Purchase",
    articles_title: "Selected Articles",
    bulletins_title: "Berlin Bulletins",
    bulletins_archive: "Berlin Bulletin Archive",
    view_all_bulletins: "View full archive",
    read_full_bulletin: "Read full bulletin",
    interviews_title: "Interviews & Discussions",
    interviews_empty:
      "Interviews will appear here once they are added in the admin.",
    interview_play: "Play Interview",
    interview_pause: "Pause",
    video_unsupported: "Your browser does not support video playback.",
    films_title: "Documentaries & Films",
    films_empty: "Films coming soon.",
    films_read_more: "Open to read the full entry.",
    photo_subtitle: "Historical records and personal snapshots",
    photo_full_collection: "Full Collection",
    memories_sub: "Voices from those whose lives he touched",
    articles_empty: "Articles coming soon.",
    footer_tag:
      "Dedicated to preserving the narrative of a life that crossed borders.",
    back_home: "Back to Home",
    read_more: "Read Full Eulogy",
    read_less: "Read Less",
    view_all_articles: "View All Articles",
    articles_archive: "Article Archive",
    articles_desc: "A collection of writings, bulletins, and thoughts.",
  },
  de: {
    bio1_title: "Der Anfang",
    bio1_range: "1928 — 1951",
    bio1_text:
      "Geboren als Stephen Wechsler in New York City, begann Victors Reise in der lebendigen politischen Atmosphäre einer jüdisch-amerikanischen Familie. Als er die Harvard University erreichte, hatte sich sein Weltbild zu einem Engagement für soziale Gerechtigkeit geschärft.",
    bio2_title: "Der Sprung in die Donau",
    bio2_text:
      "Angesichts eines drohenden Militärgerichtsverfahrens wegen seiner früheren Zugehörigkeiten handelte Stephen. Am 12. August 1952 durchschwamm er bei Linz die Donau und floh von der US-Besatzungszone in die sowjetische Besatzungszone in Österreich.",
    bio3_title: "Zeuge zweier Welten",
    bio3_text:
      "Als Victor Grossman in der DDR wiedergeboren, wurde er zu einer einzigartigen historischen Anomalie – der einzigen Person, die sowohl die Harvard University als auch die Karl-Marx-Universität in Leipzig absolvierte. Jahrzehntelang arbeitete er als Autor, Aktivist, Journalist, Übersetzer und Brücke zwischen Ost und West.",
    memorial_title: "Trauerrede & Gedenken",
    photo_archive: "Fotografisches Archiv",
    photo_sub: "Eine kuratierte Geschichte durch Bilder und Erinnerungen",
    photo_upload: "Foto hochladen",
    memories_title: "Wand der Erinnerungen",
    memories_btn: "Beitrag schreiben",
    books_title: "Bücher & Publikationen",
    books_amazon: "Kaufen",
    articles_title: "Ausgewählte Artikel",
    bulletins_title: "Berlin Bulletins",
    bulletins_archive: "Berlin-Bulletin-Archiv",
    view_all_bulletins: "Vollständiges Archiv",
    read_full_bulletin: "Ganzen Bericht lesen",
    interviews_title: "Interviews & Gespräche",
    interviews_empty:
      "Interviews erscheinen hier, sobald sie im Admin-Bereich hinzugefügt wurden.",
    interview_play: "Interview abspielen",
    interview_pause: "Pause",
    video_unsupported: "Ihr Browser unterstützt die Videowiedergabe nicht.",
    films_title: "Dokumentationen & Filme",
    films_empty: "Filme folgen in Kürze.",
    films_read_more: "Zum vollständigen Eintrag.",
    photo_subtitle: "Historische Aufzeichnungen und persönliche Aufnahmen",
    photo_full_collection: "Vollständige Sammlung",
    memories_sub: "Stimmen derer, deren Leben er berührt hat",
    articles_empty: "Artikel folgen in Kürze.",
    footer_tag:
      "Gewidmet der Bewahrung der Erzählung eines Lebens, das Grenzen überschritt.",
    back_home: "Zurück zum Start",
    read_more: "Vollständigen Nachruf lesen",
    read_less: "Weniger lesen",
    view_all_articles: "Alle Artikel ansehen",
    articles_archive: "Artikelarchiv",
    articles_desc: "Eine Sammlung von Schriften, Berichten und Gedanken.",
  },
} as const;

export type SiteCopyLang = keyof typeof SITE_COPY;
