-- Generated by scripts/split-transfer-data-to-chunks.mjs
-- Chunked data transfer file for Supabase SQL Editor.
-- Table: photos
-- Part: 1
begin;
-- photos
insert into public.photos (id, title, image_url, created_at, updated_at) values ('148c6c06-9ed9-4f63-a812-ba6555eaf5cb', null, 'https://ik.imagekit.io/mq26ahrml/cms/photos/blob_PGfL0cu6N', '2026-03-30T19:36:07.543889+00:00', '2026-03-30T19:36:07.543889+00:00') on conflict (id) do update set title = excluded.title, image_url = excluded.image_url, created_at = excluded.created_at, updated_at = excluded.updated_at;
insert into public.photos (id, title, image_url, created_at, updated_at) values ('4dc61531-c35f-4939-840a-a31f34189fc5', null, 'https://ik.imagekit.io/mq26ahrml/cms/photos/blob_IjmyvEv5U', '2026-03-30T19:36:26.225105+00:00', '2026-03-30T19:36:26.225105+00:00') on conflict (id) do update set title = excluded.title, image_url = excluded.image_url, created_at = excluded.created_at, updated_at = excluded.updated_at;
insert into public.photos (id, title, image_url, created_at, updated_at) values ('c000d37c-1f38-4a44-9b2f-77e8e65feb00', null, 'https://ik.imagekit.io/mq26ahrml/cms/photos/blob_vxMhCu0qR', '2026-03-30T19:36:50.633403+00:00', '2026-03-30T19:36:50.633403+00:00') on conflict (id) do update set title = excluded.title, image_url = excluded.image_url, created_at = excluded.created_at, updated_at = excluded.updated_at;
commit;
