-- Generated by scripts/export-supabase-to-sql.mjs
-- Chunked data transfer file for Supabase SQL Editor.
-- Source: https://xobxmxcmarcoekvxaqqf.supabase.co
-- Table: tributes
-- Part: 1
-- Generated at: 2026-03-31T03:56:53.726Z
begin;
-- tributes
insert into public.tributes (id, name, message, image_url, status, approved_at, rejected_at, source, source_key, created_at, updated_at) values ('f429c273-b6eb-4407-9226-e61a3b2d35ec', 'Anonymous', 'Victor Grossman', '', 'approved', null, null, 'wechsler-grossman:memories', 'wechsler-memories:aab59bf9-ef03-43ef-9855-88c69a449d94', '2026-01-22T21:33:24.264355+00:00', '2026-03-30T20:04:50.825395+00:00') on conflict (id) do update set name = excluded.name, message = excluded.message, image_url = excluded.image_url, status = excluded.status, approved_at = excluded.approved_at, rejected_at = excluded.rejected_at, source = excluded.source, source_key = excluded.source_key, created_at = excluded.created_at, updated_at = excluded.updated_at;
insert into public.tributes (id, name, message, image_url, status, approved_at, rejected_at, source, source_key, created_at, updated_at) values ('9270bbc0-5012-4a00-b1e9-842309b2e426', 'Marcia Gross', 'First, I would like to express my sincere condolences to Victor''s sons and family.

I was among Victor''s admirers who didn''t know him personally but exchanged a few emails with him. Pepe Escobar, the Brazilian geopolitical journalist, published one of Victor''s Berliner Bulletins on his Telegram channel in 2024. I found it so interesting and informative that, after some research, I was able to contact Victor and also became a recipient of his bulletins. I valued them all very much. To my great regret, the last bulletin contained the news of his death.

I then attended his funeral to pay my respects. It was comforting to see how many people loved him, to see how you arranged the farewell exactly as I imagine he would have liked.
The songs, the poems. The cello pieces. Heine, Paul Robeson. The gesture of distributing red carnations was very moving. It reminded me of the end of the dictatorship in Portugal. I would also like to thank you very much for the encounter in the Berliner Ensemble. We had the opportunity to exchange ideas about Victor and some very stimulating political discussions took place there.

One more thing: Because of your father, I visited the exhibition "Every Artist Must Take Sides  –  Resonances of Eslanda and Paul Robeson" at the Akademie der Künste twice, to which Victor made a significant contribution. Like Eslanda and Paul Robeson, he also took sides, which is more important than ever today and unfortunately cannot be taken for granted.

Incidentally, there was a lady at this exhibition who had traveled all the way from New Jersey just to meet your father in person.

We will miss him very much, but he will live on in our thoughts and hearts. No pasaran!', '', 'approved', null, null, 'wechsler-grossman:memories', 'wechsler-memories:1cde15bf-c9c3-45d3-9036-99e84439e27b', '2026-01-27T19:19:26.019157+00:00', '2026-03-30T20:04:50.825395+00:00') on conflict (id) do update set name = excluded.name, message = excluded.message, image_url = excluded.image_url, status = excluded.status, approved_at = excluded.approved_at, rejected_at = excluded.rejected_at, source = excluded.source, source_key = excluded.source_key, created_at = excluded.created_at, updated_at = excluded.updated_at;
insert into public.tributes (id, name, message, image_url, status, approved_at, rejected_at, source, source_key, created_at, updated_at) values ('502d168e-f890-459b-bc26-c5505a5d99fa', 'Wall of Memories', 'Wall of Memories', '', 'approved', null, null, 'wechsler-grossman:memories', 'wechsler-memories:785431c4-8e02-4f67-bdfe-51386529d3c4', '2026-02-13T01:19:53.739019+00:00', '2026-03-30T20:04:50.825395+00:00') on conflict (id) do update set name = excluded.name, message = excluded.message, image_url = excluded.image_url, status = excluded.status, approved_at = excluded.approved_at, rejected_at = excluded.rejected_at, source = excluded.source, source_key = excluded.source_key, created_at = excluded.created_at, updated_at = excluded.updated_at;
commit;
